---
title: "blog2"
author: "Mauro Lepore"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{blog2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Blog 2: Great news from the coral team!

The coral team has gret news to share: one reefs from Bocas del Toro looks similar to pristine! Curious? Here is what we found.

`why`

To make coral reefs healtier we first need to understand what causes some reefs to be in better condition than others. So we are searching for bright spots. Bright spot(xxxlinkcinner) are, among coral reefs, those which condition is better than expected given the environmental and socio-economic conditions they are exposed to.

`how`

xxxnext.   Both in reefs that lived recently and those that lived 7 000 year, we measured the amount and type of each reef coral. ....

`what, where`

Our preliminary results show that one reef from Bocas del Toro, Punta Caracol, is a potential bright spot. The reefs we study are close to each other so they are exposed to similar environmental and conditions and human pressures. Yet, compared to the pristine reefs that lived in the region 7 000 years ago, Punta Caracol seems substantially healthier than any other of the subrecent reefs we study.




`how` 
`who`





Other outputs of the project so far have been 

- I presented a public talk at  the Biomuseo, tweeter

- I read a book for kids at the international book fair, tweeter from US embassy

- Nicte and Melisa developed a guide to ID corals with versions [online](xxxlink) and in [hard copy](link)

- Nicte and Melisa developed a reference collection and presented it at APANAC

    + thank Katie Cramer for material
    + xxxinsert photos from APANAC (directly or on tweeter / facebook)
    + xxxinsert image of the poster from APANAC
    + thank Kristin for illustrations








